### ISSUE TITLE
Buff icons are too big

### ISSUE THREAD

**Issue by Hevkalol** [theripper93/combat-tracker-dock#10]
**I have disabled all other modules: **True **Module(s) **Carousel Combat Tracker **Conflicting Module(s) ** **Foundry and System version **Foundry 10.291 Pathfinder 1e 0.82.5 **OS, Hosting, Browser (if applicable) **Win10 Selfhosting **Short description of bug **Buff/ Condition icons are too big. **Simple steps to reproduce the bug ** **Screenshots and/or Console Errors**
![image](https://github.com/theripper93/combat-tracker-dock/assets/131466739/bc7fe165-5f05-4b1c-b50b-af325a7a3afb)

**Comment by MrVauxs** [comment]
The same happens over at Pathfinder 2e
![image](https://github.com/theripper93/combat-tracker-dock/assets/32039708/25e7b3b5-c7d6-46c1-9da1-6ebd6c561ae0)

**Comment by theripper93** [comment]
The V10 Version does not work on Firefox, use a Chromium browser
