### ISSUE TITLE
Undefined field 'firstTurnHidden'

### ISSUE THREAD

**Issue by farling42** [theripper93/combat-tracker-dock#15]
Foundry 11.300
Cyphersystem 2.6.2
Modules
![image](https://github.com/theripper93/combat-tracker-dock/assets/17485384/c1b6ac11-7615-49ee-83c6-1c75b0c47725)

Error in console:
![image](https://github.com/theripper93/combat-tracker-dock/assets/17485384/078be269-3fc6-4ba4-99b9-e2c366e558fe)

**Comment by farling42** [comment]
This was for an upgrade from Foundry 10.291 directly to Foundry 11.300

**Comment by theripper93** [comment]
fixed
