### ISSUE TITLE
[Feature Request] Reset Tooltip Attributes

### ISSUE THREAD

**Issue by Txus5012** [theripper93/combat-tracker-dock#16]
Hi. Nice module!

It would be nice if there was a button to restore the Tooltip Attributes to the default ones.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
