### ISSUE TITLE
[Bug/PF2E] Not Able to Bypass Dialogues for Group Rolls via Carousel

### ISSUE THREAD

**Issue by harrisog** [theripper93/combat-tracker-dock#19]
The d20 preview dialogues generated by the initiative buttons to "Roll All" and "Roll NPCs" are not bypassable via Shift-clicking when user config setting "Preview D20 Rolls" is on (system default). Considered unexpected behavior since this functionality works in the Encounters Tab.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
