### ISSUE TITLE
Suggestion for improvements

### ISSUE THREAD

**Issue by mclemente** [theripper93/combat-tracker-dock#2]
### Turn `defaultAttributesConfig` into a function that returns an object
As it is, it is impossible to use calls to game.i18n.localize on it because it is loaded on load instead of when registerSettings is called.

Changing it from `export const defaultAttributesConfig` into `export function defaultAttributesConfig()` does it.

### Move registerSettings to the setup hook
At init, localization isn't available. Pushing it back to setup allows for localization, such as setting then on `defaultAttributesConfig` to avoid copy-pasting localization from other systems in.

###  Set a way for systems to return their initiative
Some systems might not use the default D20 initiative. For example, SWADE uses cards, so something like "Red J" is being shown as a number, when the name is being saved as a flag instead.
This would require some work.

**Comment by theripper93** [comment]
Implemented suggestion 1 and 2

Implemented new `getInitiativeDisplay()` function that systems can customize in order to display non-default initiatives and customize images or icons

Included sample SWADE configuration to get contributors started (see image for final result)

```js
        case "swade": {
            let suit = "";
            const cardString = combatant?.cardString ?? "";
            if (cardString.includes("♥")) suit = "fa-solid fa-heart";
            if (cardString.includes("♦")) suit = "fa-solid fa-diamond";
            if (cardString.includes("♣")) suit = "fa-solid fa-club";
            if (cardString.includes("♠")) suit = "fa-solid fa-spade";

            return {
                value: combatant?.initiative,
                icon: suit,
                rollIcon: "fa-regular fa-cards-blank",
            } 
        }
```

![image](https://github.com/theripper93/combat-tracker-dock/assets/1346839/09f12327-ee9c-4354-ade8-3c5827ae3255)
