### ISSUE TITLE
SWADE sort order is wrong

### ISSUE THREAD

**Issue by eXaminator** [theripper93/combat-tracker-dock#21]
This module looks awesome, but it seems the order of combatants in SWADE is wrong. here is an example.

![image](https://github.com/theripper93/combat-tracker-dock/assets/2758908/2c3e2fe5-ae6e-441d-a344-80c5e08ad1d9)
![image](https://github.com/theripper93/combat-tracker-dock/assets/2758908/465adcd3-a724-4a7c-b876-1b09b6604580)

I hope this issue is fine. The link in the readme doesn't provide any helpful guidance on creating issues, only a message template for rejected issues. (https://github.com/theripper93/Levels/blob/v9/ISSUES.md)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
