### ISSUE TITLE
[PF2e] Conditions names not showing in tooltip

### ISSUE THREAD

**Issue by Demetreo** [theripper93/combat-tracker-dock#22]
**I have disabled all other modules:** True
**Module(s)** Carousel Combat Tracker
**Conflicting Module(s)** -
**Foundry and System version** Foundry 11.302 Pathfinder 2e 5.0.1
**OS, Hosting, Browser (if applicable)** Win10 Selfhosting Chromium 
**Short description of bug** Buff/Condition icons are not showing on tooltip
**Simple steps to reproduce the bug** Just setup an Encounter, one token with Conditions
**Screenshots and/or Console Errors**

![Screenshot_2](https://github.com/theripper93/combat-tracker-dock/assets/23141712/11acbcbc-be41-4118-bfd3-53541271883c)
![Screenshot_3](https://github.com/theripper93/combat-tracker-dock/assets/23141712/cf56a773-f330-484d-8fc8-48e93d204ec0)

**Comment by theripper93** [comment]
Do the conditions have an actual name? As in in the character sheet?

**Comment by theripper93** [comment]
Further investigation shows that the PF2e system is not providing the Name in their effect implementation - Most likely someting that was missed during the PF2e V10->V11 migration.

You can track this PF2e issue here https://github.com/foundryvtt/pf2e/issues/8360

**Comment by Demetreo** [comment]
Thank you for the quick response!
