### ISSUE TITLE
[PF2e] Condition names and descriptions not showing correctly

### ISSUE THREAD

**Issue by Demetreo** [theripper93/combat-tracker-dock#23]
**I have disabled all other modules:** True
**Module(s)** Carousel Combat Tracker
**Conflicting Module(s)** -
**Foundry and System version** Foundry 11.302 Pathfinder 2e 5.0.2
**OS, Hosting, Browser (if applicable)** Win10 Selfhosting Chromium
**Short description of bug** Buff/Condition names and descriptions not showing correctly on Carousel Tooltip.
**Simple steps to reproduce the bug** Token with Conditions
**Screenshots and/or Console Errors**
![image](https://github.com/theripper93/combat-tracker-dock/assets/23141712/4345365e-f214-4119-9540-7bd70c1e12f0)
![image](https://github.com/theripper93/combat-tracker-dock/assets/23141712/1d0d98f2-219d-43b6-b5e6-c37c9bafc18c)
![image](https://github.com/theripper93/combat-tracker-dock/assets/23141712/97fe081b-39a1-496c-a946-e93f0874c406)

**Comment by theripper93** [comment]
Duplicate https://github.com/theripper93/combat-tracker-dock/issues/22

**Comment by theripper93** [comment]
I just double checked to be sure, but it works completely fine, you ether have a module or browser extension fucking with the description text 
![image](https://github.com/theripper93/combat-tracker-dock/assets/1346839/0779a825-82b1-4d41-8e03-a07f5952819a)

**Comment by theripper93** [comment]
Well, found the issue, setting the tooltip color to black (#000000) will make the text basically invisible

**Comment by theripper93** [comment]
fixed

**Comment by Demetreo** [comment]
Thank you!
