### ISSUE TITLE
[World of Darkness 20th Edition] Roll dice doesn't show in chat

### ISSUE THREAD

**Issue by JonNWN** [theripper93/combat-tracker-dock#24]
Hi,

With the module active the result of the roll doesn't show in chat. You need to reload the website to see the result (or manually count with dice so nice). "Find the culprit" detected Carousel Combat Tracker as the problem (and it is the most recent module I installed) several times.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
