### ISSUE TITLE
Setting to disable on hover elements

### ISSUE THREAD

**Issue by BernhardPosselt** [theripper93/combat-tracker-dock#26]
I'd like to disable tooltips and the initiative tracker buttons. The tooltips are too big, don't hold valuable info for me and are obnoxious when you accidentally hover over them. 

The initiative tracker buttons are too tiny and I don't really need them except for the next previous buttons. Ideally, those would be aligend left/right of the carousel like:

< |x| |x| |x| >

PS: let me know how you feel about it and depending on my schedule, I think I can create a PR

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
