### ISSUE TITLE
FR: Highlight combatant portrait when hovering over token

### ISSUE THREAD

**Issue by LebombJames** [theripper93/combat-tracker-dock#27]
This is a useful feature of the core combat tracker. Hovering over the token highlights that token's combatant, which is useful when marking combatants as defeated. It'd be neat to see this in this module.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
