### ISSUE TITLE
Tracker showing permanent scroll bar and false alignments on player side.

### ISSUE THREAD

**Issue by SirAron111** [theripper93/combat-tracker-dock#28]
I started using this combat carousel since the old one isn't supported for v11. It's nice, but it acts weirdly on the player's side. The players are using different browsers but mostly Firefox and the issue is on all.
If set to overflow behavior scroll, the scroll bar on the GM side is nice and vanishes if not hovered over. The scroll bar on the player side is gigantic, solid colored, and doesn't fade away when not hovered over. There also seem to be some issues with alignments on the player side, depending on what settings are used it doesn't seem to properly align to the center for the current acting combatant for example and instead shuffles them off-screen.

![Unbenannt](https://github.com/theripper93/combat-tracker-dock/assets/39855956/b2faba03-beba-44ed-a16e-41c4a4c857c3)
![Unbenannt2](https://github.com/theripper93/combat-tracker-dock/assets/39855956/0c20fa04-5762-407e-a69b-b694704f6c5d)
Last image is the player side.
![Unbenannt3](https://github.com/theripper93/combat-tracker-dock/assets/39855956/d2d949de-d4c5-4e75-a998-acc2e6fe7181)

**Comment by SirAron111** [comment]
![Unbenannt](https://github.com/theripper93/combat-tracker-dock/assets/39855956/23a55628-72a0-498c-9349-c26402e2d0d0)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
