### ISSUE TITLE
[Feature Request] - consider adding a drop shadow/dark "glow" around UI elements to make them stand out more on light backgrounds.

### ISSUE THREAD

**Issue by tehguitarist** [theripper93/combat-tracker-dock#29]
Subject says it all really, I find that the navigation controls, and even the initiative numbers (which are a little slow as standard) can get lost very easily and a little hard to see depending on what the background image is.

Rave reviews from myself and players otherwise!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
