### ISSUE TITLE
[Feature Request] Hide dead characters on the tracker

### ISSUE THREAD

**Issue by Fyrexian** [theripper93/combat-tracker-dock#30]
Sometimes the carousel gets too crowded or confusing with dead enemies on the tracker. It would be great for them to be automatically removed at 0 hp or when they are marked defeated.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
