### ISSUE TITLE
[Feature Request] Add an option to display Tracked Resource for monsters

### ISSUE THREAD

**Issue by droideck** [theripper93/combat-tracker-dock#33]
If it's possible, please, add the $subject option. We play with the TV on the table, and I prefer to share the monster's HP with my players.
And the only way they can see the HP is on the combat tracker. 

Thank you for your awesome work!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
