### ISSUE TITLE
pf2e: Image breaks with effects

### ISSUE THREAD

**Issue by maddox522** [theripper93/combat-tracker-dock#35]
Hello!

When using the combat tracker dock in pf2e everything seems to work perfectly until a character has an effect on them, specifically the light effect. I have posted an image below but when the two characters with light on their characters are in the combat tracker their picture disappears and is blank. It works perfectly again when the light effect is taken away.

I also have the module pf2e giveth, which may have an effect too? 

<img width="979" alt="image" src="https://github.com/theripper93/combat-tracker-dock/assets/109387393/29ba35bb-30fb-41de-a61c-df62f4e99910">

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
