### ISSUE TITLE
[Idea] Baldur's Gate 3 Portrait Color Based on HP

### ISSUE THREAD

**Issue by quartet4** [theripper93/combat-tracker-dock#36]
Fantastic module! One idea (if you're looking for any) is to implement the CRPG mechanic where portraits are colored red from the bottom up, depending on the percentage of HP left. Although definitely inspired by putting too many hours into BG3 recently, I think it'll also help healers see everyone's HP at a glance.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
