### ISSUE TITLE
Monk's Combat Details incompatibility

### ISSUE THREAD

**Issue by eryon** [theripper93/combat-tracker-dock#37]
**I have disabled all other modules:** True
**Module(s)** combat-tracker-dock
**Conflicting Module(s)** lib-wrapper, monks-combat-details
**Foundry and System version** Core Version: 11.307  System: pf2e 5.3.2
**OS, Hosting, Browser (if applicable)** Firefox, Windows
**Short description of bug** Combat tracker incompatibility
**Simple steps to reproduce the bug**

With these modules enabled, FVTT reports the following error:
libWrapper: module Monk's Combat Details and module Carousel Combat Tracker modify the same FoundryVTT functionality and are more likely to conflict.

Toggling visibility of the combatants through the carousel does not work.

**Screenshots and/or Console Errors**
```
[W] libWrapper: module Monk's Combat Details and module Carousel Combat Tracker modify the same FoundryVTT functionality and are more likely to conflict.
Module monks-combat-details did not chain the wrapper for 'Combatant.prototype.visible'.
```

**Comment by theripper93** [comment]
As indicated by libwrapper the issue is on Combat details end, id open the issue on combat details repo

**Comment by eryon** [comment]
Cross-linking that issue here https://github.com/ironmonk88/monks-combat-details/issues/45
