### ISSUE TITLE
Noticeable performance drop when module is active

### ISSUE THREAD

**Issue by Sinled** [theripper93/combat-tracker-dock#38]
Hi, with this module enabled during battle fps in foundry drops ~20-30% when dragging/zooming map.

I am not sure if this problem is present in latest version of foundry, but in v10 it exists.

At the moment it can be solved with custom styles, but probably it should be fixed in module?

You can add a little hack, that will tell browser to optimise element for change beforehand, even though we don't change transform on element, it completely solves fps drop on map move

```css
#combat-dock {
	will-change: transform;
}
```

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.

**Comment by Sinled** [comment]
Yes, better close without reading even if it can make your product better, good job.

**Comment by theripper93** [comment]
As mentioned above, read the bug reporting guidelines, provide the required information and reopen the issue
