### ISSUE TITLE
Show enemy health to players

### ISSUE THREAD

**Issue by Slaycker** [theripper93/combat-tracker-dock#39]
By chance, is there any way I can show the enemies lives to the players, without having to give access to the enemies sheets? As for GM, but I would just like to show life itself, not the rest...

GM
![image](https://github.com/theripper93/combat-tracker-dock/assets/106133347/080e2412-5b6e-4422-9fc2-0f86f3c76646)

Player
![image](https://github.com/theripper93/combat-tracker-dock/assets/106133347/3773503a-023f-4435-bd62-0a5b4de6e625)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
