### ISSUE TITLE
Forced on wrong users

### ISSUE THREAD

**Issue by Zarhog** [theripper93/combat-tracker-dock#44]
The combat trackers seems to be Running on scenes where it shouldn't, for example if a GM is running a combat on Scene X then its showing for X and Y.

This is particularly annoying with the way i have my server set up as we have some users on other maps editing stuff whilst we run games so its distracting. and soon will be a bigger problem for us when we release our new modal start stop. (start stop is designed to allow multiple games run at the same time on one client server)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
