### ISSUE TITLE
Next turn animation does not look right

### ISSUE THREAD

**Issue by ddbrown30** [theripper93/combat-tracker-dock#45]
I was just watching the demo video for the tracker and realized that mine does not look right. I've added a video cap of it below. I have no other modules enabled when recording this. I'm using the swade system. Foundry version 11.315. Tracker version 2.7.5.

I'm using centered in the video but left looks similarly broken.

I just jumped into a dnd5e world and the animation is correct there, so it does seem to be a system specific bug.

[2024-02-13 10-27-35.webm](https://github.com/theripper93/combat-tracker-dock/assets/9253904/b20f6e79-54d0-403b-a31f-12a8b5dbdf73)

**Comment by theripper93** [comment]
Carousel combat tracker has no system specific logic in how the carousel itself operates, Since it works in every other system, this is most likely an issue of how the custom swade combat tracker operates - most likely due to when it updates the order of it's combatants which probably differs from expected behaviour.
I cannot provide a fix to this, i recomend switching to the "no carousel" mode which does not have this animation

**Comment by theripper93** [comment]
i don't plan on adding system specific workarounds for upstream issues as stated above, sorry

**Comment by ddbrown30** [comment]
Then perhaps you could spend some time investigating the issue and implementing a proper fix? You don't take PRs so I'm not sure what your desired path is here. Based on your fast reply and what you said, I'm assuming you haven't even tried to repro the issue. Maybe try debugging it a bit before dismissing the bug out of hand?

FWIW, I'm continuing my debugging locally and at this point I can at least confirm that what's coming out of this.sortedCombatants matches what I get when using dnd5e i.e. its sorted with the highest value at the beginning of the list. I imagine that if you, who obviously is going to have a much better understanding of the code, were to hop in a debugger and check it out, you could probably identify where it's going wrong fairly quickly.

**Comment by ddbrown30** [comment]
Still digging. It's not a sort issue. It's actually that update.direction is undefined. Trying to track down where that gets set now.

**Comment by theripper93** [comment]
again. this is a bug with SWADE. It's not providing the `direction` of the combat update

**Comment by theripper93** [comment]
as can be seen here, the core combat tracker and every other system i know of provides the direction here 
![image](https://github.com/theripper93/combat-tracker-dock/assets/1346839/69992526-7d91-4b3a-a6b8-bdfed8db4c92)

**Comment by ddbrown30** [comment]
Yup, that's the answer. The swade system is not setting the direction value when it's calling nextTurn and nextRound. I'll open a bug with them.
