### ISSUE TITLE
Strange GUI behavior on Initiative roll

### ISSUE THREAD

**Issue by patrickmohrmann** [theripper93/combat-tracker-dock#46]
**I have disabled all other modules: **True
**Module(s) **Carousel Combat Tracker
**Conflicting Module(s) **
**Foundry and System version **Foundry 11.315 Earthdawn4e V0.8.1.2
**OS, Hosting, Browser (if applicable) **Chrome
**Short description of bug **Using ombat tracker will somehow after a few clicks set the gui to this (see screenshot)
**Simple steps to reproduce the bug **

use several actors in combat tracker and cklick next
on every new round inititative is rolled for all actors. thats the usual case when it fails

**Screenshots and/or Console Errors**

![image](https://github.com/theripper93/combat-tracker-dock/assets/76265425/c8b17b66-b420-499e-be3f-74ab9597ce54)

**Comment by theripper93** [comment]
Considering this has never been reported before and that your system has a custom theme it's very possible it has some more invasive customizations that conflict with CCT. Is it possible to disable the system theme? Have you tried with different carousel orientation/types? I can't resolve theme issues so it's ether that or not much I can do

**Comment by patrickmohrmann** [comment]
Hey, I'm sorry, I found the issue was probably related to a very strange behavior of my browser, I had it in another foundry unrelated situation and gave everything a good check, after reinstallation everything works fine.
