### ISSUE TITLE
Request: Show enemy resources to players

### ISSUE THREAD

**Issue by mfozz** [theripper93/combat-tracker-dock#47]
It'd be nice to have the ability to show an enemy's tracked resources to players. Great module by the way

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
