### ISSUE TITLE
[PF2e] Console error when ending combat

### ISSUE THREAD

**Issue by ottyn** [theripper93/combat-tracker-dock#49]
Foundry 11.315
PF2e 5.15.3
Carousel Combat Tracker 2.7.7

When ending a combat, the following error message is posted in the console.  Error does not appear to cause any issues and combat tracker closes.

![image](https://github.com/theripper93/combat-tracker-dock/assets/97130150/b413a49f-355b-4246-98cd-81b27d38c281)

**Comment by theripper93** [comment]
This is a core bug nothing to do with the carousel you can ignore it, v12 will fix it
