### ISSUE TITLE
Setting the Carousel to no carousel moves the whole UI

### ISSUE THREAD

**Issue by lizzorrd** [theripper93/combat-tracker-dock#50]
If you select no carousel in the settings and click to the next combatant the whole UI moves a bit to the left.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.

**Comment by lizzorrd** [comment]
Sorry for not reading the Before Posting an issue part beforehand.

**I have disabled all other modules: **True
**Module(s) **Carousel Combat Tracker
**Conflicting Module(s) **PF2e Pathfinder Ui v3 An Add-on Module for Foundry Virtual Tablet
**Foundry and System version **
**OS, Hosting, Browser (if applicable) **Client: Windows 11 Version 10.0.22631 Build 22631, Firefox 126.0.1 (64-bit), Host: Raspbian Pi, Raspbian GNU/Linux 10 (buster)
**Short description of bug **When the "Carousel Style" is set to "No Carousel" the whole UI moves after the beginning of the combat.
**Simple steps to reproduce the bug **

Enable Pathfinder UI v3 (https://foundryvtt.com/packages/pathfinder-ui/) and Carousel Combat tracker. Then add some tokens to a scene and start the encounter.

**Screenshots and/or Console Errors**
![CCT_1](https://github.com/theripper93/combat-tracker-dock/assets/143729359/219d2572-ea1f-4070-9799-f5bce5d3cbf9)
![CCT2](https://github.com/theripper93/combat-tracker-dock/assets/143729359/c34e7d12-98b8-4236-aaf7-e5e4a6e278cb)
![CCT3](https://github.com/theripper93/combat-tracker-dock/assets/143729359/dd941434-6722-42cb-bef4-d0eb40cd0ffc)


If I also should open the issue on the pathfinder ui github, please tell me.

**Comment by theripper93** [comment]
Any kind of issue with UI modules, is on the UI module side to fix - i recommend letting the theme developer know so they can fix it. I don't plan any fix on my end
