### ISSUE TITLE
Suggestion - add padding at top of tracker to match Foundry VTT UI

### ISSUE THREAD

**Issue by boloniusMonk** [theripper93/combat-tracker-dock#51]
I find the tracker being flush with the top of the screen to be very unattractive and jarring.   Every time I look at it, I feel the need to move it.   It would look better if it had the same/similar padding like the rest of the Foundry VTT UI.   I can fix it for myself by adding padding to ui-top in styles module.css, if this isn't something that you want to change.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
