### ISSUE TITLE
Temporary Max HP Adjustments don't show up on Carousel

### ISSUE THREAD

**Issue by Janders797** [theripper93/combat-tracker-dock#57]
If you give you want to temporarily change max HP (Aid spell, Specter, etc), this doesn't show up in the stat on the tracker.

Character Sheet:
![image](https://github.com/user-attachments/assets/65667b75-ca1d-48fc-ae89-11b00042cec3)
Combat Tracker:
![image](https://github.com/user-attachments/assets/e15d6f61-d493-46de-bff2-5f46b92d85a2)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
