### ISSUE TITLE
Request - Add support for token scale when using token images

### ISSUE THREAD

**Issue by ddbrown30** [theripper93/combat-tracker-dock#58]
I will occasionally create token art that is intentionally larger than the occupied space. This usually to allow for some minor feature, like flowing hair, to spill over into other spaces. This is accomplished by using the Scale slider in the token settings. The downside of this is that when using token art in the carousel, the art ends up looking too small.

It would be great if there was optional support in the carousel to scale the image to match the scale on the token.

Here's an example token to illustrate. I use 1.4 scale to get this to look right.
![Mymekes Advanced Token](https://github.com/user-attachments/assets/d1f14773-0ebf-4222-9985-552077015c2b)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
