### ISSUE TITLE
Combat Tracker "Roll All" or "Roll NPCs" Rolls a ridiculous number of dice

### ISSUE THREAD

**Issue by Brandon-MC** [theripper93/combat-tracker-dock#63]
Hello - when I use the "Roll All" or "Roll NPC" initiative shortcut with the Dice So Nice module, a ridiculous number of dice are rolled for each actor in combat.  Is this a known issue, and is there a fix?  Thanks fo much for your time and for making my campaigns vtt experience brighter.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
