### ISSUE TITLE
Strange UI issue when turn changes

### ISSUE THREAD

**Issue by ottyn** [theripper93/combat-tracker-dock#64]
FVTT 12.331
PF2e 6.7.2
Carousel Combat Tracker 3.1.6
Chrome 131.0.6778.140

When changing turns between tokens, the entire UI will shift to the left.  Appears to happen if more than 3 tokens in total are in combat and will happen multiple times in the round the more tokens you have.  UI resets itself the following round but then shifts again.

If I disable Carousel Combat Tracker and use the built in combat tracker, the issue does not occur.

No errors or warnings in the console.

Video of issue:

https://github.com/user-attachments/assets/1158d514-9cee-4a9c-9043-fb6f271c2d29

**Comment by ottyn** [comment]
I have tested this on a local Foundry install in Windows using NodeJS and on both of my Linux VPS hosts using NodeJS

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
